// <auto-generated />
namespace PointOfSalesFull.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addthd_movToAcctransHed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addthd_movToAcctransHed));
        
        string IMigrationMetadata.Id
        {
            get { return "201908061037507_addthd_movToAcctransHed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
